### ISSUE TITLE
Where is the compiled version?

### ISSUE THREAD

**Issue by arjvik** [mihaifm/vim.ahk#5]
Hi, I can't seem to find the compiled version of your script. It looks great, but I can't install AHK. I would love to use the precompiled version (`vim.ahk.exe`), if it exists. Please point me to it. Thanks, Arjun.

**Comment by mihaifm** [comment]
I will build an exe for you in the releases.

This project hasn't had any love for years, I'll try to update it.

**Comment by mihaifm** [comment]
Added compiled exe in the releases:

https://github.com/mihaifm/vim.ahk/releases
